web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./app:/app
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:7-fpm
  volumes:
    - ./app:/app

php:
  image: php-xdebug-custom
  volumes:
    - ./app:/app
    - ./php.ini:/php/php.ini